// AUTO-GENERATED by scripts/generate-data.mjs
// Source: ~/mckay-os/ filesystem
// Generated: 2026-04-10T19:31:31.370Z
// Do not edit manually — run: npm run generate

import type { Notification, CalendarEntry, MemoryFile } from './types'

// Legacy fallback data — field names pre-date Supabase migration
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const PROJ: any[] = [
  {
    id: "msc",
    n: "mission-control",
    e: "🎮",
    pct: 35,
    phN: 0,
    phase: "**Live** ✓",
    health: "Healthy",
    col: "var(--p)",
    cr: "187,136,255",
    tkn: 0,
    cost: 0,
    days: 0,
    term: "Idle",
    dom: "mission-control.mckay.agency",
    stack: "React+Vite, TailwindCSS, Vercel+Supabase",
    model: "",
    prompts: 0,
    last: "**Live** ✓",
    next: "",
    todos: 13,
    ideas: 0,
    rev: 0,
    mkt: ""
  }
]

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const AGENTS: any[] = [
  {
    n: "KANI Master",
    e: "⬡",
    typ: "Core",
    st: "active",
    mdl: "Opus",
    proj: "All",
    tkn: "0K",
    cost: "€0.00",
    pr: 0,
    suc: 0,
    act: "synthesizes agent outputs, manages conte",
    col: "var(--c)",
    bg: "rgba(0,200,232,0.15)"
  },
  {
    n: "Launch Agent",
    e: "🚀",
    typ: "Core",
    st: "active",
    mdl: "Opus",
    proj: "All",
    tkn: "0K",
    cost: "€0.00",
    pr: 0,
    suc: 0,
    act: "from raw idea to live project",
    col: "var(--g)",
    bg: "rgba(0,232,136,0.15)"
  },
  {
    n: "Build Agent",
    e: "⌨",
    typ: "Core",
    st: "active",
    mdl: "Opus",
    proj: "All",
    tkn: "0K",
    cost: "€0.00",
    pr: 0,
    suc: 0,
    act: "the execution engine",
    col: "var(--bl)",
    bg: "rgba(68,153,255,0.15)"
  },
  {
    n: "Ops Agent",
    e: "⚙",
    typ: "Core",
    st: "active",
    mdl: "Sonnet",
    proj: "All",
    tkn: "0K",
    cost: "€0.00",
    pr: 0,
    suc: 0,
    act: "performance, errors, uptime, dependency ",
    col: "var(--c)",
    bg: "rgba(0,200,232,0.12)"
  },
  {
    n: "Research Agent",
    e: "🔬",
    typ: "Specialist",
    st: "idle",
    mdl: "Sonnet",
    proj: "—",
    tkn: "0K",
    cost: "€0.00",
    pr: 0,
    suc: 0,
    act: "",
    col: "var(--a)",
    bg: "rgba(255,184,0,0.12)"
  },
  {
    n: "Sales Agent",
    e: "💰",
    typ: "Specialist",
    st: "idle",
    mdl: "Sonnet",
    proj: "—",
    tkn: "0K",
    cost: "€0.00",
    pr: 0,
    suc: 0,
    act: "",
    col: "var(--o)",
    bg: "rgba(255,119,68,0.12)"
  },
  {
    n: "Strategy Agent",
    e: "🎯",
    typ: "Specialist",
    st: "idle",
    mdl: "Sonnet",
    proj: "—",
    tkn: "0K",
    cost: "€0.00",
    pr: 0,
    suc: 0,
    act: "",
    col: "var(--p)",
    bg: "rgba(187,136,255,0.12)"
  },
  {
    n: "Life Agent",
    e: "☀",
    typ: "Specialist",
    st: "idle",
    mdl: "Haiku",
    proj: "—",
    tkn: "0K",
    cost: "€0.00",
    pr: 0,
    suc: 0,
    act: "",
    col: "var(--t3)",
    bg: "rgba(255,255,255,0.04)"
  },
  {
    n: "Mockup Brief",
    e: "🎨",
    typ: "Specialist",
    st: "idle",
    mdl: "Sonnet",
    proj: "—",
    tkn: "0K",
    cost: "€0.00",
    pr: 0,
    suc: 0,
    act: "screen specs, component lists, tool-agno",
    col: "var(--bl)",
    bg: "rgba(68,153,255,0.1)"
  },
  {
    n: "devils advocate agent",
    e: "◈",
    typ: "Specialist",
    st: "idle",
    mdl: "Sonnet",
    proj: "—",
    tkn: "0K",
    cost: "€0.00",
    pr: 0,
    suc: 0,
    act: "finds security holes, UX problems, perfo",
    col: "var(--t3)",
    bg: "rgba(255,255,255,0.04)"
  },
  {
    n: "voice agent",
    e: "◈",
    typ: "Specialist",
    st: "idle",
    mdl: "Sonnet",
    proj: "—",
    tkn: "0K",
    cost: "€0.00",
    pr: 0,
    suc: 0,
    act: "AI voice layer for terminal. Two modes: ",
    col: "var(--t3)",
    bg: "rgba(255,255,255,0.04)"
  }
]

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const SKILLS: any[] = [
  {
    n: "business-model",
    cat: "Core",
    st: 1,
    p: 4,
    orig: "MCKAY"
  },
  {
    n: "scaffold-project",
    cat: "Core",
    st: 1,
    p: 4,
    orig: "MCKAY"
  },
  {
    n: "code-quality",
    cat: "Core",
    st: 1,
    p: 4,
    orig: "MCKAY"
  },
  {
    n: "deploy",
    cat: "Core",
    st: 1,
    p: 4,
    orig: "MCKAY"
  },
  {
    n: "memory-cleanup",
    cat: "Core",
    st: 1,
    p: 4,
    orig: "MCKAY"
  },
  {
    n: "booking-system",
    cat: "Project",
    st: 1,
    p: 2,
    orig: "MCKAY"
  },
  {
    n: "marketplace",
    cat: "Project",
    st: 1,
    p: 2,
    orig: "MCKAY"
  },
  {
    n: "multi-tenant",
    cat: "Project",
    st: 1,
    p: 2,
    orig: "MCKAY"
  },
  {
    n: "medical-compliance",
    cat: "Domain",
    st: 1,
    p: 2,
    orig: "MCKAY"
  },
  {
    n: "gdpr-health",
    cat: "Domain",
    st: 1,
    p: 2,
    orig: "MCKAY"
  },
  {
    n: "real-estate",
    cat: "Domain",
    st: 1,
    p: 2,
    orig: "MCKAY"
  },
  {
    n: "voice-ai",
    cat: "Domain",
    st: 1,
    p: 2,
    orig: "MCKAY"
  },
  {
    n: "maps-routing",
    cat: "Domain",
    st: 1,
    p: 2,
    orig: "MCKAY"
  },
  {
    n: "supabase-postgres",
    cat: "Integration",
    st: 1,
    p: 4,
    orig: "3rd Party"
  },
  {
    n: "react-best-practices",
    cat: "Integration",
    st: 1,
    p: 4,
    orig: "3rd Party"
  },
  {
    n: "webhook-patterns",
    cat: "Integration",
    st: 1,
    p: 4,
    orig: "3rd Party"
  },
  {
    n: "playwright-cli",
    cat: "Integration",
    st: 1,
    p: 4,
    orig: "3rd Party"
  },
  {
    n: "ui-design",
    cat: "Integration",
    st: 1,
    p: 4,
    orig: "3rd Party"
  },
  {
    n: "design-system",
    cat: "MCKAY",
    st: 1,
    p: 4,
    orig: "MCKAY"
  },
  {
    n: "deployment-workflow",
    cat: "MCKAY",
    st: 1,
    p: 4,
    orig: "MCKAY"
  },
  {
    n: "content-system",
    cat: "MCKAY",
    st: 0,
    p: 4,
    orig: "MCKAY"
  },
  {
    n: "marketing-essentials",
    cat: "MCKAY",
    st: 0,
    p: 4,
    orig: "MCKAY"
  },
  {
    n: "website-redesign-pipeline",
    cat: "MCKAY",
    st: 0,
    p: 4,
    orig: "MCKAY"
  }
]

export const IDEAS: unknown[] = []

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const TODOS: any[] = [
  {
    id: 1,
    txt: "**P1** Buchhaltung: Belege-Upload, Auto-Rename, KPIs",
    proj: "mis",
    prio: "m",
    due: "",
    done: false,
    ov: false
  },
  {
    id: 2,
    txt: "**P2** Subscriptions: Provider-Liste, Kosten, API-Key-Datei-Links",
    proj: "mis",
    prio: "m",
    due: "",
    done: false,
    ov: false
  },
  {
    id: 3,
    txt: "**P2** Verträge: Laufzeiten, Kündigungsdaten, Gruppierung",
    proj: "mis",
    prio: "m",
    due: "",
    done: false,
    ov: false
  },
  {
    id: 4,
    txt: "**P2** Kunden: Hebam Agency + HebamBüro Dashboards",
    proj: "mis",
    prio: "m",
    due: "",
    done: false,
    ov: false
  },
  {
    id: 5,
    txt: "**P2** Wohnung: Mieter, Hausverwaltung, Nebenkosten",
    proj: "mis",
    prio: "m",
    due: "",
    done: false,
    ov: false
  },
  {
    id: 6,
    txt: "**P2** Familie + Gesundheit: Termine, Organisation, Fitness",
    proj: "mis",
    prio: "m",
    due: "",
    done: false,
    ov: false
  },
  {
    id: 7,
    txt: "**P3** Private Todos + E-Mails",
    proj: "mis",
    prio: "m",
    due: "",
    done: false,
    ov: false
  },
  {
    id: 8,
    txt: "**P2** Kontakte: Kontaktliste mit Rollen",
    proj: "mis",
    prio: "m",
    due: "",
    done: false,
    ov: false
  },
  {
    id: 9,
    txt: "**P2** Events + Portale: Links, Zugangsstatus",
    proj: "mis",
    prio: "m",
    due: "",
    done: false,
    ov: false
  },
  {
    id: 10,
    txt: "**P3** Partner + Opportunities: CRM-light",
    proj: "mis",
    prio: "m",
    due: "",
    done: false,
    ov: false
  },
  {
    id: 11,
    txt: "**P1** Alle Bereiche mit Mehti durchgehen",
    proj: "mis",
    prio: "m",
    due: "",
    done: false,
    ov: false
  },
  {
    id: 12,
    txt: "**P1** Action Buttons pro Bereich finalisieren",
    proj: "mis",
    prio: "m",
    due: "",
    done: false,
    ov: false
  },
  {
    id: 13,
    txt: "**P1** Dev → Main merge",
    proj: "mis",
    prio: "m",
    due: "",
    done: false,
    ov: false
  },
  {
    id: 14,
    txt: "**P1** Anhänge Backend",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 15,
    txt: "**P1** Anhänge UI",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 16,
    txt: "**P1** Dynamische Ordner",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 17,
    txt: "**P1** Email-Memory Supabase",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 18,
    txt: "**P1** Kontakt-Profile",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 19,
    txt: "**P1** Smart Labels",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 20,
    txt: "**P1** SmartKPIBar",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 21,
    txt: "**P1** Master-Detail Layout",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 22,
    txt: "**P1** KANI Empfehlungen",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 23,
    txt: "**P1** Kommentar-Flow",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 24,
    txt: "**P1** Reply-Flow",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 25,
    txt: "**P2** Kalender Neon-Farben",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 26,
    txt: "**P2** Jahresansicht klickbar",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 27,
    txt: "**P2** Today vorausgewählt",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 28,
    txt: "**P2** Todo aus Email",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 29,
    txt: "**P2** Todo Filter",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 30,
    txt: "**P2** Bearbeitet-Counter",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 31,
    txt: "**P2** Schriftgrößen",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 32,
    txt: "**P2** Kompakte Karten",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 33,
    txt: "**P1** Google Calendar Full CRUD",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 34,
    txt: "**P1** Email AI Triage",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 35,
    txt: "**P1** MIME Body-Parser",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 36,
    txt: "**P1** Kalender Views",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 37,
    txt: "**P1** Email UI",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 38,
    txt: "**P2** Memory Cleanup",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 39,
    txt: "**P1** Google Calendar API",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 40,
    txt: "**P1** Non-Projekt Todos CRUD",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 41,
    txt: "**P1** IMAP Integration",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 42,
    txt: "**P2** E-Mail Übersicht",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 43,
    txt: "**P2** Punycode-Fix + categories.ts geschützt",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 44,
    txt: "**P1** useTerminalSession, IdeaDetail, WindowManager, Time Tracker",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 45,
    txt: "**P1** Office/Life/Hub/Network Pages + 9-Tile Cockpit",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 46,
    txt: "**P1** Terminal-Lifecycle, Feierabend-Button, Todo-Widget",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  }
]

export const NOTIFS: Notification[] = [
  {
    typ: "sofort",
    ico: "⚡",
    tit: "Session aktiv: Phase C: Live Dashboard",
    sub: "~/mckay-os/projects/mission-control",
    t: "Jetzt"
  },
  {
    typ: "wichtig",
    ico: "⚠",
    tit: "findemeinehebamme-v2: GitHub Repo URL needed",
    sub: "Wartet auf Mehti",
    t: "2026-03-28"
  },
  {
    typ: "wichtig",
    ico: "⚠",
    tit: "mckay-inbox: Postfach-Inventur (20 accounts)",
    sub: "Wartet auf Mehti",
    t: "2026-03-28"
  },
  {
    typ: "wichtig",
    ico: "⚠",
    tit: "hebammenbuero: Validation with real midwives",
    sub: "Wartet auf Mehti",
    t: "2026-03-29"
  },
  {
    typ: "info",
    ico: "✓",
    tit: "Filesystem-Daten aktiv",
    sub: "Dashboard zeigt echte MCKAY OS Daten",
    t: "21:31"
  }
]

export const CAL: CalendarEntry[] = [
  {
    t: "10:00",
    n: "Daily Standup",
    s: "Zoom · Alle Projekte Review",
    today: false
  },
  {
    t: "14:00",
    n: "Hebammenbuero Validation Call",
    s: "Zoom · Mockup Review mit 2 Hebammen",
    today: false
  },
  {
    t: "09:30",
    n: "KANI Sprint Planning",
    s: "Terminal · Mission Control Phase E",
    today: false
  },
  {
    t: "15:00",
    n: "TennisCoach Phase 4 Review",
    s: "Zoom · Stripe + Chat Planung",
    today: false
  },
  {
    t: "11:00",
    n: "Steuerberaterin Ott Meeting",
    s: "Ulm · Tax Architect Website-Build",
    today: false
  },
  {
    t: "10:00",
    n: "Wochenplanung",
    s: "Home Office · KANI Briefing + Prioritäten",
    today: false
  }
]

export const MEM: MemoryFile[] = [
  {
    ico: "🧠",
    n: "MEMORY.md",
    m: "2026-04-09 · 1.6KB",
    b: "Aktiv"
  },
  {
    ico: "📋",
    n: "REGISTRY.md",
    m: "2026-04-08 · 15.6KB",
    b: "Aktiv"
  },
  {
    ico: "🧬",
    n: "DNA.md",
    m: "2026-04-08 · 18.0KB",
    b: "Aktiv"
  },
  {
    ico: "📁",
    n: "mission-control/CLAUDE.md",
    m: "2026-04-10 · 6.0KB",
    b: "Aktiv"
  },
  {
    ico: "💬",
    n: "context/",
    m: "1 Files",
    b: "1"
  }
]

export const SCCAT: Record<string, string> = {
  Core: "var(--c)",
  MCKAY: "var(--p)",
  Integration: "var(--bl)",
  Project: "var(--a)",
  Domain: "var(--g)"
}

export const MTRIX: Record<string, number[]> = {
  "KANI Master": [
    1
  ],
  "Launch Agent": [
    1
  ],
  "Build Agent": [
    1
  ],
  "Ops Agent": [
    1
  ],
  "Research Agent": [
    1
  ],
  "Sales Agent": [
    0
  ],
  "Strategy Agent": [
    0
  ],
  "Life Agent": [
    0
  ],
  "Mockup Brief": [
    1
  ],
  "devils advocate agent": [
    0
  ],
  "voice agent": [
    0
  ]
}
