// AUTO-GENERATED by scripts/generate-data.mjs
// Source: ~/mckay-os/ filesystem
// Generated: 2026-04-09T14:43:21.454Z
// Do not edit manually — run: npm run generate

import type { Notification, CalendarEntry, MemoryFile } from './types'

// Legacy fallback data — field names pre-date Supabase migration
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const PROJ: any[] = [
  {
    id: "msc",
    n: "mission-control",
    e: "🎮",
    pct: 35,
    phN: 0,
    phase: "**Live** ✓",
    health: "Healthy",
    col: "var(--p)",
    cr: "187,136,255",
    tkn: 0,
    cost: 0,
    days: 0,
    term: "Idle",
    dom: "mission-control.mckay.agency",
    stack: "React+Vite, TailwindCSS, Vercel+Supabase",
    model: "",
    prompts: 0,
    last: "**Live** ✓",
    next: "",
    todos: 4,
    ideas: 0,
    rev: 0,
    mkt: ""
  }
]

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const AGENTS: any[] = [
  {
    n: "KANI Master",
    e: "⬡",
    typ: "Core",
    st: "active",
    mdl: "Opus",
    proj: "All",
    tkn: "0K",
    cost: "€0.00",
    pr: 0,
    suc: 0,
    act: "synthesizes agent outputs, manages conte",
    col: "var(--c)",
    bg: "rgba(0,200,232,0.15)"
  },
  {
    n: "Launch Agent",
    e: "🚀",
    typ: "Core",
    st: "active",
    mdl: "Opus",
    proj: "All",
    tkn: "0K",
    cost: "€0.00",
    pr: 0,
    suc: 0,
    act: "from raw idea to live project",
    col: "var(--g)",
    bg: "rgba(0,232,136,0.15)"
  },
  {
    n: "Build Agent",
    e: "⌨",
    typ: "Core",
    st: "active",
    mdl: "Opus",
    proj: "All",
    tkn: "0K",
    cost: "€0.00",
    pr: 0,
    suc: 0,
    act: "the execution engine",
    col: "var(--bl)",
    bg: "rgba(68,153,255,0.15)"
  },
  {
    n: "Ops Agent",
    e: "⚙",
    typ: "Core",
    st: "active",
    mdl: "Sonnet",
    proj: "All",
    tkn: "0K",
    cost: "€0.00",
    pr: 0,
    suc: 0,
    act: "performance, errors, uptime, dependency ",
    col: "var(--c)",
    bg: "rgba(0,200,232,0.12)"
  },
  {
    n: "Research Agent",
    e: "🔬",
    typ: "Specialist",
    st: "idle",
    mdl: "Sonnet",
    proj: "—",
    tkn: "0K",
    cost: "€0.00",
    pr: 0,
    suc: 0,
    act: "",
    col: "var(--a)",
    bg: "rgba(255,184,0,0.12)"
  },
  {
    n: "Sales Agent",
    e: "💰",
    typ: "Specialist",
    st: "idle",
    mdl: "Sonnet",
    proj: "—",
    tkn: "0K",
    cost: "€0.00",
    pr: 0,
    suc: 0,
    act: "",
    col: "var(--o)",
    bg: "rgba(255,119,68,0.12)"
  },
  {
    n: "Strategy Agent",
    e: "🎯",
    typ: "Specialist",
    st: "idle",
    mdl: "Sonnet",
    proj: "—",
    tkn: "0K",
    cost: "€0.00",
    pr: 0,
    suc: 0,
    act: "",
    col: "var(--p)",
    bg: "rgba(187,136,255,0.12)"
  },
  {
    n: "Life Agent",
    e: "☀",
    typ: "Specialist",
    st: "idle",
    mdl: "Haiku",
    proj: "—",
    tkn: "0K",
    cost: "€0.00",
    pr: 0,
    suc: 0,
    act: "",
    col: "var(--t3)",
    bg: "rgba(255,255,255,0.04)"
  },
  {
    n: "Mockup Brief",
    e: "🎨",
    typ: "Specialist",
    st: "idle",
    mdl: "Sonnet",
    proj: "—",
    tkn: "0K",
    cost: "€0.00",
    pr: 0,
    suc: 0,
    act: "screen specs, component lists, tool-agno",
    col: "var(--bl)",
    bg: "rgba(68,153,255,0.1)"
  },
  {
    n: "devils advocate agent",
    e: "◈",
    typ: "Specialist",
    st: "idle",
    mdl: "Sonnet",
    proj: "—",
    tkn: "0K",
    cost: "€0.00",
    pr: 0,
    suc: 0,
    act: "finds security holes, UX problems, perfo",
    col: "var(--t3)",
    bg: "rgba(255,255,255,0.04)"
  },
  {
    n: "voice agent",
    e: "◈",
    typ: "Specialist",
    st: "idle",
    mdl: "Sonnet",
    proj: "—",
    tkn: "0K",
    cost: "€0.00",
    pr: 0,
    suc: 0,
    act: "AI voice layer for terminal. Two modes: ",
    col: "var(--t3)",
    bg: "rgba(255,255,255,0.04)"
  }
]

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const SKILLS: any[] = [
  {
    n: "business-model",
    cat: "Core",
    st: 1,
    p: 4,
    orig: "MCKAY"
  },
  {
    n: "scaffold-project",
    cat: "Core",
    st: 1,
    p: 4,
    orig: "MCKAY"
  },
  {
    n: "code-quality",
    cat: "Core",
    st: 1,
    p: 4,
    orig: "MCKAY"
  },
  {
    n: "deploy",
    cat: "Core",
    st: 1,
    p: 4,
    orig: "MCKAY"
  },
  {
    n: "memory-cleanup",
    cat: "Core",
    st: 1,
    p: 4,
    orig: "MCKAY"
  },
  {
    n: "booking-system",
    cat: "Project",
    st: 1,
    p: 2,
    orig: "MCKAY"
  },
  {
    n: "marketplace",
    cat: "Project",
    st: 1,
    p: 2,
    orig: "MCKAY"
  },
  {
    n: "multi-tenant",
    cat: "Project",
    st: 1,
    p: 2,
    orig: "MCKAY"
  },
  {
    n: "medical-compliance",
    cat: "Domain",
    st: 1,
    p: 2,
    orig: "MCKAY"
  },
  {
    n: "gdpr-health",
    cat: "Domain",
    st: 1,
    p: 2,
    orig: "MCKAY"
  },
  {
    n: "real-estate",
    cat: "Domain",
    st: 1,
    p: 2,
    orig: "MCKAY"
  },
  {
    n: "voice-ai",
    cat: "Domain",
    st: 1,
    p: 2,
    orig: "MCKAY"
  },
  {
    n: "maps-routing",
    cat: "Domain",
    st: 1,
    p: 2,
    orig: "MCKAY"
  },
  {
    n: "supabase-postgres",
    cat: "Integration",
    st: 1,
    p: 4,
    orig: "3rd Party"
  },
  {
    n: "react-best-practices",
    cat: "Integration",
    st: 1,
    p: 4,
    orig: "3rd Party"
  },
  {
    n: "webhook-patterns",
    cat: "Integration",
    st: 1,
    p: 4,
    orig: "3rd Party"
  },
  {
    n: "playwright-cli",
    cat: "Integration",
    st: 1,
    p: 4,
    orig: "3rd Party"
  },
  {
    n: "ui-design",
    cat: "Integration",
    st: 1,
    p: 4,
    orig: "3rd Party"
  },
  {
    n: "design-system",
    cat: "MCKAY",
    st: 1,
    p: 4,
    orig: "MCKAY"
  },
  {
    n: "deployment-workflow",
    cat: "MCKAY",
    st: 1,
    p: 4,
    orig: "MCKAY"
  },
  {
    n: "content-system",
    cat: "MCKAY",
    st: 0,
    p: 4,
    orig: "MCKAY"
  },
  {
    n: "marketing-essentials",
    cat: "MCKAY",
    st: 0,
    p: 4,
    orig: "MCKAY"
  },
  {
    n: "website-redesign-pipeline",
    cat: "MCKAY",
    st: 0,
    p: 4,
    orig: "MCKAY"
  }
]

export const IDEAS: unknown[] = []

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const TODOS: any[] = [
  {
    id: 1,
    txt: "**P2** Individuelle Action Buttons pro Bereich (Projects, Thinktank, etc.)",
    proj: "mis",
    prio: "m",
    due: "",
    done: false,
    ov: false
  },
  {
    id: 2,
    txt: "**P2** Kalender",
    proj: "mis",
    prio: "m",
    due: "",
    done: false,
    ov: false
  },
  {
    id: 3,
    txt: "**P3** E-Mail",
    proj: "mis",
    prio: "m",
    due: "",
    done: false,
    ov: false
  },
  {
    id: 4,
    txt: "**P3** Personal/Backoffice/Network",
    proj: "mis",
    prio: "m",
    due: "",
    done: false,
    ov: false
  },
  {
    id: 5,
    txt: "**P1** Kumulativer Time Tracker (ZoneProvider) + Shutdown-Anzeige + Briefing",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 6,
    txt: "**P1** Kitchen Tile im Cockpit + TerminalGrid Attention-System (3 Severity-Overlays)",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 7,
    txt: "**P1** useTerminalSession Hook",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 8,
    txt: "**P1** IdeaDetail Terminal-Lifecycle (Dormant/Active/Shutdown, gleiches Pattern wie Projects)",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 9,
    txt: "**P2** WindowManager überall",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 10,
    txt: "**P1** Todo-Widget persistent (Terminal-getrieben, auto in-progress/done)",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 11,
    txt: "**P2** Agent Status mit echten Daten (useAgentStatus + Polling)",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 12,
    txt: "**P2** Bottom Ticker mit echten Daten (activity_log + feed + notifications)",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 13,
    txt: "**P1** Feierabend-Button Fix (shell:true, Error-Handler, Abort)",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  },
  {
    id: 14,
    txt: "**P1** Terminal-Lifecycle (Dormant/Active/Shutdown, Session-Detection, Neue Session)",
    proj: "mis",
    prio: "l",
    due: "",
    done: true,
    ov: false
  }
]

export const NOTIFS: Notification[] = [
  {
    typ: "sofort",
    ico: "⚡",
    tit: "Session aktiv: Phase C: Live Dashboard",
    sub: "~/mckay-os/projects/mission-control",
    t: "Jetzt"
  },
  {
    typ: "wichtig",
    ico: "⚠",
    tit: "findemeinehebamme-v2: GitHub Repo URL needed",
    sub: "Wartet auf Mehti",
    t: "2026-03-28"
  },
  {
    typ: "wichtig",
    ico: "⚠",
    tit: "mckay-inbox: Postfach-Inventur (20 accounts)",
    sub: "Wartet auf Mehti",
    t: "2026-03-28"
  },
  {
    typ: "wichtig",
    ico: "⚠",
    tit: "hebammenbuero: Validation with real midwives",
    sub: "Wartet auf Mehti",
    t: "2026-03-29"
  },
  {
    typ: "info",
    ico: "✓",
    tit: "Filesystem-Daten aktiv",
    sub: "Dashboard zeigt echte MCKAY OS Daten",
    t: "16:43"
  }
]

export const CAL: CalendarEntry[] = [
  {
    t: "10:00",
    n: "Daily Standup",
    s: "Zoom · Alle Projekte Review",
    today: false
  },
  {
    t: "14:00",
    n: "Hebammenbuero Validation Call",
    s: "Zoom · Mockup Review mit 2 Hebammen",
    today: false
  },
  {
    t: "09:30",
    n: "KANI Sprint Planning",
    s: "Terminal · Mission Control Phase E",
    today: false
  },
  {
    t: "15:00",
    n: "TennisCoach Phase 4 Review",
    s: "Zoom · Stripe + Chat Planung",
    today: false
  },
  {
    t: "11:00",
    n: "Steuerberaterin Ott Meeting",
    s: "Ulm · Tax Architect Website-Build",
    today: false
  },
  {
    t: "10:00",
    n: "Wochenplanung",
    s: "Home Office · KANI Briefing + Prioritäten",
    today: false
  }
]

export const MEM: MemoryFile[] = [
  {
    ico: "🧠",
    n: "MEMORY.md",
    m: "2026-04-09 · 1.8KB",
    b: "Aktiv"
  },
  {
    ico: "📋",
    n: "REGISTRY.md",
    m: "2026-04-08 · 15.6KB",
    b: "Aktiv"
  },
  {
    ico: "🧬",
    n: "DNA.md",
    m: "2026-04-08 · 18.0KB",
    b: "Aktiv"
  },
  {
    ico: "📁",
    n: "mission-control/CLAUDE.md",
    m: "2026-04-09 · 5.8KB",
    b: "Aktiv"
  },
  {
    ico: "💬",
    n: "context/",
    m: "1 Files",
    b: "1"
  }
]

export const SCCAT: Record<string, string> = {
  Core: "var(--c)",
  MCKAY: "var(--p)",
  Integration: "var(--bl)",
  Project: "var(--a)",
  Domain: "var(--g)"
}

export const MTRIX: Record<string, number[]> = {
  "KANI Master": [
    1
  ],
  "Launch Agent": [
    1
  ],
  "Build Agent": [
    1
  ],
  "Ops Agent": [
    1
  ],
  "Research Agent": [
    0
  ],
  "Sales Agent": [
    1
  ],
  "Strategy Agent": [
    0
  ],
  "Life Agent": [
    0
  ],
  "Mockup Brief": [
    0
  ],
  "devils advocate agent": [
    1
  ],
  "voice agent": [
    1
  ]
}

// ============================================================
// Category data for Office / Life / Hub / Network pages
// ============================================================

export interface CategoryItem {
  id: string
  name: string
  desc: string
  color: string
  glow: string
  badge: string
  emoji: string
  stats: { label: string; value: string }[]
}

export const officeCategories: CategoryItem[] = [
  { id: 'buchhaltung', name: 'Buchhaltung', desc: 'Belege, Datev, Steuerberaterin', color: 'var(--bl)', glow: 'var(--blg)', badge: 'Monatlich', emoji: '\u{1F4CA}', stats: [{ label: 'Letzter Upload', value: '2026-03-28' }, { label: 'Belege', value: '42' }] },
  { id: 'subscriptions', name: 'Subscriptions', desc: 'SaaS, Lizenzen, API-Kosten', color: 'var(--p)', glow: 'var(--pg)', badge: '9 aktiv', emoji: '\u{1F511}', stats: [{ label: 'Monatlich', value: '\u20AC347' }, { label: 'Services', value: '9' }] },
  { id: 'vertraege', name: 'Vertr\u00E4ge', desc: 'Handy, Auto, Lizenzen, Laufzeiten', color: 'var(--a)', glow: 'var(--ag)', badge: '7 aktiv', emoji: '\u{1F4C4}', stats: [{ label: 'Aktiv', value: '7' }, { label: 'N\u00E4chste K\u00FCndigung', value: '2026-06-15' }] },
  { id: 'kunden', name: 'Kunden', desc: 'Hebam Agency, HebamB\u00FCro, aktive Kunden', color: 'var(--g)', glow: 'var(--gg)', badge: '2 Businesses', emoji: '\u{1F465}', stats: [{ label: 'Hebam Agency', value: '~100' }, { label: 'HebamB\u00FCro', value: '12' }] },
  { id: 'business-email', name: 'Business E-Mails', desc: 'Support, Anfragen, R\u00FCckmeldungen', color: 'var(--o)', glow: 'var(--og)', badge: '3 Postf\u00E4cher', emoji: '\u{1F4E7}', stats: [{ label: 'Ungelesen', value: '5' }, { label: 'Heute', value: '2' }] },
]

export const lifeCategories: CategoryItem[] = [
  { id: 'wohnung', name: 'Wohnung', desc: 'Mieter, Hausverwaltung, Nebenkosten', color: 'var(--bl)', glow: 'var(--blg)', badge: 'Vermietet', emoji: '\u{1F3E0}', stats: [{ label: 'Mieter', value: '1' }, { label: 'Kaltmiete', value: '\u20AC750' }] },
  { id: 'familie', name: 'Familie', desc: 'Kinder, Termine, Organisation', color: 'var(--pk)', glow: 'var(--pkg)', badge: '4 Personen', emoji: '\u{1F468}\u200D\u{1F469}\u200D\u{1F467}\u200D\u{1F466}', stats: [{ label: 'N\u00E4chster Termin', value: 'Heute' }, { label: 'Offene Todos', value: '3' }] },
  { id: 'gesundheit', name: 'Gesundheit', desc: 'Fitness, Arzttermine, Wellness', color: 'var(--g)', glow: 'var(--gg)', badge: 'Aktiv', emoji: '\u{1F4AA}', stats: [{ label: 'Gym/Woche', value: '3x' }, { label: 'Streak', value: '12 Tage' }] },
  { id: 'private-todos', name: 'Private Todos', desc: 'Bank, Steuerberater, Erledigungen', color: 'var(--a)', glow: 'var(--ag)', badge: '5 offen', emoji: '\u2705', stats: [{ label: 'Offen', value: '5' }, { label: 'Diese Woche', value: '2' }] },
  { id: 'private-email', name: 'Private E-Mails', desc: 'Pers\u00F6nliche Postf\u00E4cher', color: 'var(--t)', glow: 'var(--tg)', badge: '2 Postf\u00E4cher', emoji: '\u2709\uFE0F', stats: [{ label: 'Ungelesen', value: '12' }, { label: 'Heute', value: '4' }] },
]

export const hubCategories: CategoryItem[] = [
  { id: 'kalender', name: 'Kalender', desc: 'Privat + Business, alle Termine', color: 'var(--g)', glow: 'var(--gg)', badge: 'Google Calendar', emoji: '\u{1F4C5}', stats: [{ label: 'Heute', value: '2 Termine' }, { label: 'Diese Woche', value: '7' }] },
  { id: 'todos', name: 'Todos', desc: 'Alles nicht-Projekt: Bank, Arzt, Admin', color: 'var(--o)', glow: 'var(--og)', badge: '8 offen', emoji: '\u{1F4CB}', stats: [{ label: 'Offen', value: '8' }, { label: 'Heute f\u00E4llig', value: '2' }] },
  { id: 'email-hub', name: 'E-Mail \u00DCbersicht', desc: 'Alle Postf\u00E4cher auf einen Blick', color: 'var(--bl)', glow: 'var(--blg)', badge: '5 Postf\u00E4cher', emoji: '\u{1F4EC}', stats: [{ label: 'Ungelesen gesamt', value: '17' }, { label: 'Dringend', value: '3' }] },
]

export const networkCategories: CategoryItem[] = [
  { id: 'kontakte', name: 'Kontakte', desc: 'Kunden, Partner, Dienstleister', color: 'var(--t)', glow: 'var(--tg)', badge: '45 Kontakte', emoji: '\u{1F464}', stats: [{ label: 'Kunden', value: '15' }, { label: 'Partner', value: '8' }] },
  { id: 'events', name: 'Events', desc: 'Meetups, Konferenzen, Termine', color: 'var(--p)', glow: 'var(--pg)', badge: '3 geplant', emoji: '\u{1F3A4}', stats: [{ label: 'Diesen Monat', value: '1' }, { label: 'N\u00E4chstes', value: '15. Apr' }] },
  { id: 'portale', name: 'Portale & Kurse', desc: 'Voice Agent, Marketing, Weiterbildung', color: 'var(--o)', glow: 'var(--og)', badge: '4 aktiv', emoji: '\u{1F393}', stats: [{ label: 'Aktive Kurse', value: '2' }, { label: 'Abgeschlossen', value: '1' }] },
  { id: 'partner', name: 'Partner', desc: 'Business-Partner, Agenturen, Freelancer', color: 'var(--bl)', glow: 'var(--blg)', badge: '6 aktiv', emoji: '\u{1F91D}', stats: [{ label: 'Aktiv', value: '6' }, { label: 'Potentiell', value: '3' }] },
  { id: 'opportunities', name: 'Opportunities', desc: 'Leads, Anfragen, Chancen', color: 'var(--g)', glow: 'var(--gg)', badge: '2 hei\u00DF', emoji: '\u{1F525}', stats: [{ label: 'Pipeline', value: '5' }, { label: 'Hei\u00DF', value: '2' }] },
]
